version: '3.8'

services:
  frontend:
    image: abhinavpancholi/lumiclaim-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: abhinavpancholi/lumiclaim-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - app_data:/server/data
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://db:27017/lumiclaim

  db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
  mongo_data:

